# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kdelibs4support' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/akonadi-calendar' : '@latest'
    'kde/pim/calendarsupport' : '@latest'
    'kde/pim/kcalutils' : '@latest'
    'kde/pim/libkdepim' : '@latest'
